#! /bin/bash
echo "#####"
echo $1
echo "#####"
dir=$1
while :
do
  dir=`dirname $dir`
  echo $dir
  if [ $dir == "/" ] ; then
    exit 1;
  fi;
  echo $dir/bConfigurationValue

  if [ -e $dir/bConfigurationValue ]; then
    echo 1 >  $dir/bConfigurationValue ;
    exit 0;
  fi;
done

